### ISSUE TITLE
External Sites: Icons do not pass integrity check

### ISSUE THREAD

**Issue by maesitopi** [owncloud/apps#2158] opened 2016-03-15 20:29 UTC
### Affected apps
External Sites App

### Expected behaviour
Exclude this img path of integrity check or make it possible to define another img path for external sites icons.

### Actual behaviour
The new integrity check of OC 9 returns an error "EXTRA FILE". The External Sites App only let you choose an icon of the "/apps/external/img" path
Server configuration

### Steps to reproduce
1. Activate "External Sites"
2. Upload a custom logo to "/apps/external/img"
3. Integrity Check of OC 9.0 returns "EXTRA FILE"

### Server configuration
Ubuntu 14.04 LTS
Apache/2.4.7
MySQL 5.6.19
PHP 5.5.9
Owncloud 9.0.0
Updated from Owncloud 8.2.3

### Client configuration
Browser: Firefox, Chrome, IE

Operating system:
Windows 10 & Windows 8.1

**Comment by MorrisJobke** [comment] 2016-03-16 10:00
Duplicate of https://github.com/owncloud/apps/issues/2154

**Closed by MorrisJobke** 2016-03-16 10:00 UTC
