### ISSUE TITLE
Enabling  "Deleted Files " App trigger oC upgrade

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/apps#2072] opened 2015-05-26 19:11 UTC
[3194]
### Steps to reproduce
1. Costume performed oC upgrade 6.0.4 to 7.0.5
2. Try to enable " Deleted Files" app 
3. Trigger oC upgrade

### Expected behaviour
Able to enable "deleted files" app

### Actual behaviour
Prior to upgrade  customer deleted many files which generated "Deleted Files" app, after oC upgraded from 6.0.4 to 70.5 customer  was try to enable "deleted files" app which trigger oC upgrade

### Server configuration
**Operating system**: CentOS 6.6

**Web server:** Apache 2.2.15

**Database:** Oracle

**PHP version:** 5.5.20

**ownCloud version:** 7.0.5

**Updated from an older ownCloud or fresh install:** Yes

#### Screen Shot
![apps](https://cloud.githubusercontent.com/assets/10195796/7821143/b6d65942-03ba-11e5-8457-edd552d9a04f.png)

**Comment by LukasReschke** [comment] 2015-05-26 19:13
That looks kinda empty.

**Comment by VicDeo** [comment] 2015-05-26 19:47
I guess a complete list of steps is:
1. install 6.0.4 
2. enable " Deleted Files" app
3. disable " Deleted Files" app
4. Upgrade to 7.0.5
5. enable " Deleted Files" app

Expected:
App is upgraded

Actual:
App is upgraded

Resolution: not a bug 

:)

**Comment by iliyasbasir** [comment] 2015-05-26 20:23
@VicDeo 
Customer did upgrade hey go!  " The deleted files app was enabled for the upgrade from 6.0.4 to 6.0.7,"

**Comment by iliyasbasir** [comment] 2015-05-26 20:39
@VicDeo Any help would be appreciated to fix this issue.

**Comment by iliyasbasir** [comment] 2015-05-27 15:05
*** Here is Step***

[root@owntest2 yum.repos.d]# sudo -u apache php /var/www/html/owncloud-enterprise/occ app:enable files_trashbin
files_trashbin enabled
[root@owntest2 yum.repos.d]# sudo -u apache php /var/www/html/owncloud-enterprise/occ app:disable files_trashbin
files_trashbin disabled
[root@owntest2 yum.repos.d]# sudo -u apache php /var/www/html/owncloud-enterprise/occ app:list
Enabled:
 - admin_audit
 - enterprise_key
 - files
 - files_sharing
 - files_texteditor
 - files_versions
 - firstrunwizard
 - templateeditor
 - user_ldap
Disabled:
 - activity
 - external
 - files_antivirus
 - files_encryption
 - files_external
 - files_ldap_home
 - files_locking
 - files_sharing_log
 - files_trashbin
 - firewall
 - provisioning_api
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth
 - windows_network_drive
[root@owntest2 yum.repos.d]# sudo -u apache php /var/www/html/owncloud-enterprise/occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
Turned off maintenance mode
Update successful
[root@owntest2 yum.repos.d]# sudo -u apache php /var/www/html/owncloud-enterprise/occ app:enable files_trashbin
files_trashbin enabled
[root@owntest2 yum.repos.d]#  sudo -u apache php /var/www/html/owncloud-enterprise/occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
An exception occurred while executing 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)':

ORA-01758: table must be empty to add mandatory (NOT NULL) column
Turned off maintenance mode
Update successful
[root@owntest2 yum.repos.d]#

**Comment by LukasReschke** [comment] 2015-05-27 16:34
> An exception occurred while executing 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)':
> ORA-01758: table must be empty to add mandatory (NOT NULL) column

Looks fishy. cc @DeepDiver1975

**Comment by bboule** [comment] 2015-05-27 18:33
Hey guys here is where we are, user missed step 3 (in the steps above) she did not disable this app in question prior to the upgrade... now she is stuck... what are the options here?  I dont think we can tell someone to do this and consider this not a bug...  Let me know what you think?

**Comment by LukasReschke** [comment] 2015-05-27 18:56
The error appears also at https://github.com/owncloud/core/issues/16454#issuecomment-103925926, this is a **GREAT** example why it is **REALLY** important to post the text and **NOT** a screenshot. We can't search for screenshots.

See then https://github.com/owncloud/core/issues/16343#issuecomment-101780670 and https://github.com/owncloud/core/issues/16204#issuecomment-100363570:
>This upgrade on Oracle has to be custom scripted - please get in touch with GCX.

No action required from ENG from my POV.

**Comment by iliyasbasir** [comment] 2015-05-28 16:04
@LukasReschke : Those three GitHub related to same customer for diff scenario, I do like to placed picture b/c it gave little more visibility " as we say in America picture meant 1000 word"

I don’t understand when you say “No action required from ENG” so you meant  this is bug ?  
Can you guide me what action do I need to take in order to fix this issue.

**Comment by LukasReschke** [comment] 2015-05-28 16:39
If this issue is about the `An exception occurred while executing 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)':` error message then this means that the customer uses an Oracle database. – Schema updates (that's what's happening here – the database layout changes) on MSSQL and Oracle are not possible automated in this scenario. 
(at least that's what I think is what the issue is about as the update will always be unsuccessful)

Thus somebody needs to create a script that handles their schema update as well as test it etc. – That is handled by GCX.

=> You need to get this to the attention of some of the GCX folks such as @MorrisJobke or @butonic and/or triage this to @craigpg / Mark.

**Comment by iliyasbasir** [comment] 2015-05-29 13:24
@MorrisJobke @butonic Can you please look this issue and let me know if you need any assistance on my side

**Comment by iliyasbasir** [comment] 2015-06-01 14:39
@bboule @craigpg Can you please point me engineer who can help me on this issue

**Comment by bboule** [comment] 2015-06-01 15:02
@iliyasbasir the problem here seems to be that the user did not generate the proper upgrade scripts, they need to use the occ commands to generate the schema update however please make sure the user disables the deleted files app prior to running the schema update script.  It sounds to me like this is the step that was missed, let them run the upgrade again with the correct procedure and see where it ends up.

**Comment by MorrisJobke** [comment] 2015-06-08 21:02
Duplicate of https://github.com/owncloud/core/issues/16812

**Closed by MorrisJobke** 2015-06-08 21:02 UTC
Labels: blue-ticket
