### ISSUE TITLE
Activity app: show if a file got downloaded

### ISSUE THREAD

**Issue by novij** [owncloud/apps#1599] opened 2014-01-09 11:30 UTC
We need to see if a shared file (by another user or by shared link) got downloaded.

Would it be much work to add this feature?

I've took a quick look on the code but I'm not sure if changes in other apps are needed to do this.

**Comment by PVince81** [comment] 2015-07-30 10:01
Duplicate of https://github.com/owncloud/core/issues/13158

**Closed by PVince81** 2015-07-30 10:01 UTC
