### ISSUE TITLE
Show apps with available updates first

### ISSUE THREAD

**Issue by tflidd** [owncloud/apps#2155] opened 2016-03-09 10:09 UTC
### Affected apps
Apps-page

### Steps to reproduce/Expected behaviour
1. I get a notification `You have 1 app update pending`
2. If I go to enabled apps, I want the apps in question to be shown at top of the list

alternative: add a new filter for updatable apps

### Actual behaviour
You have to go through the list in order to find the update.

### Server configuration
Operating system: Debian 8/mod_php/apache

ownCloud version: 9.0.0

**Comment by MorrisJobke** [comment] 2016-03-09 10:36
Duplicate of https://github.com/owncloud/core/issues/22892

**Closed by MorrisJobke** 2016-03-09 10:36 UTC
