### ISSUE TITLE
App spec: spreadsheet editor

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/apps#126] opened 2012-11-02 21:44 UTC
We need a proper spreadsheet editor app.

Currently the only good online spreadsheet app is Google Docs. There’s an open source one similar to Etherpad called [EtherCalc](http://ethercalc.net) but it’s built on Node.js and UI-wise has still a long way to go.

**Comment by Yamaha32088** [comment] 2015-02-02 21:42
Real-time collaborative spreadsheet functionality would make OwnCloud just that much more epic. I would be more than happy to help collaborate to make this happen. Has anyone started working on this? Also I saw mention of Node.JS in this thread as if it was a negative thing, is that something that to stay away from?

**Comment by wuendsch** [comment] 2015-02-04 11:06
+1

**Comment by ataraxus** [comment] 2015-02-04 11:54
@Yamaha32088 hey, I think NodeJS is not a feasible option, because it would add another dependencie onto owncloud, which should be prevented if possible....

**Comment by Bugsbane** [comment] 2015-02-05 02:40
Possibly relevant issue over at WebODF: https://github.com/kogmbh/WebODF/issues/863

**Comment by gdepratt** [comment] 2015-02-09 23:05
+1 For this feature.  It is slowing the adoption of OwnCloud where I work and keeping users on GDocs.

**Comment by carlosafonso** [comment] 2015-02-24 10:40
+1. I'd be more than glad to help.

**Comment by diarmaid-mcmanus** [comment] 2015-03-04 21:00
I want to echo @TheKnerd's question - what is it that actually has yet to be done here? I'm willing to contribute development time, as this is a feature I'd like to see implemented. Pinging in @DeepDiver1975 - is hacking in an existing jquery solution mentioned above going to be considered?

**Comment by alvaralmstedt** [comment] 2015-03-10 10:52
+1

**Comment by PatelParas** [comment] 2015-03-24 12:37
I would love to contribute for this feature if anybody working on that

**Comment by nemo5** [comment] 2015-04-10 11:30
+1

**Comment by valessiobrito** [comment] 2015-04-10 23:58
+1  other proposal  https://github.com/zkoss/zkspreadsheet

**Comment by Yamaha32088** [comment] 2015-04-27 19:59
I found this amazing script today I think it would work perfect to build on it and add the spreadsheet app. http://handsontable.com/demo/contextmenucopypaste.html

**Comment by Bugsbane** [comment] 2015-05-02 20:22
@Yamaha32088 - DOes that actually perform calculations? The description just calls it a "data grid editor" and when I tried entering "=3+2" and "3+2" in their demo, it didn't actually calculate the answer...

**Comment by Yamaha32088** [comment] 2015-05-04 13:55
@Bugsbane No it does not perform calculations, I did find a couple that did but this one looks the best. It is really easy to get the values from rows and columns so adding calculations to it should be fairly easy. I guess the next step is to start creating this thing instead of just talking about it, however it is my first time contributing to something in a team effort so pardon my newb question, but how should we get this started and get some people working on it? I was also thinking about PHP Excel as being part of the backend for this spreadsheet app to generate and read any spreadsheet docs. I have used it on several other projects and it works great and is super easy to use. https://phpexcel.codeplex.com/

**Comment by lionax** [comment] 2015-05-04 19:24
Hey folks,

I like what @Yamaha32088 posted for the front-end. IMHO would phpexcel be nice for back-end. I also would like to contribute but also don't know where to start. If the right idea comes up I will post it immediately ;).

Want to mention ShareJS just for info. (It's node.js but seems really neat)
http://sharejs.org/

**Comment by Yamaha32088** [comment] 2015-05-07 18:11
@Bugsbane I stand corrected. It looks like they just updated their website with more documentation since my last visit. There is not a formulas option http://handsontable.github.io/handsontable-ruleJS/

**Comment by Bugsbane** [comment] 2015-05-08 00:17
@Yamaha32088 Nice! Ok, now this is looking interesting! :+1:

**Comment by gboissiere** [comment] 2015-05-21 22:20
+1.  Being able to get a good document, spreadsheet and presentation editor in Owncloud is the killer app that's sorely missing right now.

**Comment by wtayyeb** [comment] 2015-05-23 18:59
+1 and online collaborating is an important key feature.

**Comment by poVoq** [comment] 2015-06-02 16:26
Comes with a huge dependency list (for example mono 4.0), but has an awesome collaborative document, spreadsheet and presentation editor: http://www.onlyoffice.com/blog/2015/04/document-server-3-0-release-and-other-news-for-open-source-community-2/
The main onlyoffice also integrates a bit with owncloud already.
Maybe worth writing an cross integration plugin for owncloud now that is is available under the GPL and for linux servers?

**Comment by Bugsbane** [comment] 2015-06-03 12:55
@poVoq One of the core ideas behind ownCloud is keeping the dependencies only to what is found on the most common hosting platforms, and with a minimal set of dependencies. Also, I suspect that pulling in something that relied on mono would be extremely unpopular. That said, with the new stronger separation between core and apps, if this is only dependencies for an app rather than OC itself, who knows.

That said, personally, for something as important and central to the OC platform as the spreadsheet app, I would hate to see it rely on mono and a long list of dependencies (which would actually make it unavailable to many users).

**Comment by wtayyeb** [comment] 2015-06-04 07:10
I suggest to keep in mind to select an app that will dress owncloud theme in future. also needs less changes to be compatible with OC, so the upstream updates and bugfixes will simpler to patch into it.

I guess the better decision will be writing some sort of plugin-like-apps (one officially from OC-team and others by contributes) which joining the 3rd-party spreadsheet app with owncloud, and the end user select which one to install. the official one must to be less dependency and well tuned UI, incredibly fast and cover most of features. for example EatherCalc is very slow, its UI belong to Win3.1 and features are limited, but seem to easily joined with owncloud. in other hand the onlyoffice is some how better in UI and features, but fails in dependency.

**Comment by Milannv** [comment] 2015-07-06 10:38
I'm currently working on a basic implementation for showing spreadsheets within ownCloud 8.x. I must say this project was mainly a research project for my university so there is lot's of room for improvement and new features!

![screen shot 2015-07-06 at 12 31 33](https://cloud.githubusercontent.com/assets/1913267/8520512/17939430-23db-11e5-8718-7158c4b2ff98.png)

Alpha release on github is expected within a week.

Used technologies:
- PHPExcel 
- Handsontable 

Application flow:
One clicks on a spreadsheet file, file is parsed and then converted to JSON. Afterwards, Handsontable parses the result and makes it visible to the end user. 

Features:
- ruleJS is included for calculations
- Open up spreadsheets (xls, xlsx, ods)
- Implemented multiple "worksheets" based on Handsontable pagination (http://docs.handsontable.com/0.15.1/demo-pagination.html) 

My ToDo:
- I'm currently trying to implement file exporting and file saving
- Refactoring my code

**Comment by Yamaha32088** [comment] 2015-07-06 11:33
@Milnav Great progress, it sounds promising. I can't wait to check out the alpha release.

**Comment by onewaypub** [comment] 2015-07-06 11:56
@Milnav Great news! We could help with testing and bug reporting. I ask some friends, who use my cloud instance, if they could test the feature in productive near cases.

**Comment by karlitschek** [comment] 2015-07-06 14:52
@Milannv This is super cool! Do you want to create an official ownCloud app out of that? And maybe develop this in it's own repo in the owncloud github organisation?

**Comment by Milannv** [comment] 2015-07-08 13:50
@karlitschek I was planning to create an (official) ownCloud app out of it. However, because this was mainly a research project for an university project, I haven't really decided on feature development. This is mainly caused by time constraints.

**Comment by karlitschek** [comment] 2015-07-08 13:53
@Milannv Sure. I understand. But if you make this open source and put tit in github then maybe other people help to develop this further. You are no longer on your own :-)
Your decision of course.

**Comment by Milannv** [comment] 2015-07-19 17:13
Bit later than anticipated, but the alpha release is here: https://apps.owncloud.com/content/show.php?content=170678

I hope it is useful, enjoy!

**Comment by outscale-jju** [comment] 2015-10-19 15:53
That's a great news, thanks for your work !
I hope you (or someone else) will continue to develop / maintain this app :)

**Comment by lordadamson** [comment] 2015-11-14 19:17
+1 we need this

**Comment by Bugsbane** [comment] 2015-11-14 19:26
Getting this completed, stable and realtime collaborative would make for a killer feature announcement for OC v9/10. Just sayin'...

**Comment by karlitschek** [comment] 2015-11-14 19:32
This is a huge feature. So unfortunately +1 doesn't make this happen. Someone needs to step up and work on that. Pull requests welcome. Just saying :-)

**Comment by Bugsbane** [comment] 2015-11-14 20:26
I hear you on that Frank. If I could code, I'd be working on this right now. My expertise is more in marketing though. That said, a public call for help on this could go a long way. I suspect that many devs who could, and possibly would, help probably don't even realize that this app exists. What are the main skills required, not to finish everything, but to at least get things moving again so we can attract more interest?

**Comment by lordadamson** [comment] 2015-11-14 22:00
I'm gathering a team to work on it. wish me luck.

**Comment by Bugsbane** [comment] 2015-11-14 23:24
> I'm gathering a team to work on it. wish me luck.

Good luck! Let me know if you need an English press release or similar written / proof read. ;)

**Comment by ConnyOnny** [comment] 2015-11-15 20:16
@lordadamson good luck :wink:

**Comment by lordadamson** [comment] 2015-12-05 21:20
heeeeeeeey. I've got some good news :dancer: :dancer: :D
https://github.com/COMU/libreonline-owncloud
just look at this beauty :D

**Comment by Bugsbane** [comment] 2015-12-07 02:27
Having trouble figuring out if this has anything to do with being able to open and edit spreadsheets in ownCloud or not...

**Comment by mmeeks** [comment] 2016-12-12 17:58
Would be great to close this now we have Collabora Online, and/or CODE deployed out there - and now with Collaborative Editing =)

**Closed** 2016-12-12 18:00 UTC
Labels: App Spec, enhancement
