### ISSUE TITLE
Add button "import calendar" in calendar settings

### ISSUE THREAD

**Issue by ghost** [owncloud/apps#732] opened 2013-03-11 14:37 UTC
Hi, I've spent some time trying to import an ICS file to my calendar in owncloud.
It seems the only way to do that is to import the ICS file in owncloud's files, then click on it. This seems to work for me (drag n drop the .isc file on the calendar window should alsp work, but it doesn't for me, separate issue).

Even with drag n drop working, this is not very intuitive, many users would expect a button to trigger an import dialog.

I think the cleanest place to have this button is next to the "New calendar" button in the calendar settings menu.

What do you think?

**Comment by leandro-lucarella-sociomantic** [comment] 2015-04-30 10:39
+1, Owncloud is **GREAT** so this seems like a very weird missing feature, going through the Files app to import a calendar seems to be the most convoluted and annoying workflow for users. If all the importing logic is there already, I guess adding an import button directly in the Calendar app should be trivial.

**Comment by jancborchardt** [comment] 2015-04-30 13:16
This is a duplicate of https://github.com/owncloud/calendar/issues/197 – let’s continue there.

**Closed by jancborchardt** 2015-04-30 13:16 UTC
Labels: app:calendar, Enhancement
