### ISSUE TITLE
[Files_videoviewer] Click in time slider restarts the video or does nothing

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/apps#2064] opened 2015-05-15 07:15 UTC
### Steps to reproduce

1. Upload a video.
2. Reproduce it.
3. Try to jump to the middle of the video, clicking in the time slider.

### Expected behaviour
Video continues from the middle 

### Actual behaviour
Video is restarted (Chrome) or nothing happens (Firefox).

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by DeepDiver1975** [comment] 2015-05-21 11:07
we might want to update the mediaelement library - current version is https://github.com/johndyer/mediaelement/blob/2.16.4/changelog.md - we ship 2.14.2

**Comment by MorrisJobke** [comment] 2015-07-17 11:54
I tested the upgrade to 2.17.0 but the bug is still there. Needs further investigation.

**Comment by DeepDiver1975** [comment] 2015-07-17 21:10
Looks like we need to allocate more time on this: 8.1.2 or even 8.2 from my understanding

**Comment by cmonteroluque** [comment] 2015-07-21 16:42
agreed

**Comment by freechelmi** [comment] 2015-09-17 14:05
Actually on my oc 8.1

For a shared video ( no media element just browser HTML5 control : 
- it works great on Firefox 40 here 
- it still does not work on chromium 47

For a displayed video ( media element) 
- it works great on Firefox 40 here 
- it still does not work on chromium 47

**Comment by cmonteroluque** [comment] 2015-10-25 18:34
https://github.com/owncloud/apps/issues/2064#issuecomment-104230876

@DeepDiver1975 should this also be added to the 3rdparty list of dependencies?

**Comment by karlitschek** [comment] 2015-10-25 19:23
@cmonteroluque Which list do you mean? Dependencies for 3rdparty apps should be in the app itself.

**Comment by cmonteroluque** [comment] 2015-10-28 02:05
@karlitschek ok, thanks

**Comment by PatelParas** [comment] 2015-10-28 05:25
@freechelmi chrome required Partial content 206 http response. for video playing. here it returns http 200.

**Comment by PVince81** [comment] 2015-11-04 17:05
Is this a regression ? Or was it always broken in Chrome ?

CC @VicDeo with the hope for more clues :smile:

**Comment by PVince81** [comment] 2015-11-04 17:06
From what I remember the video player is currently using range requests, maybe the server needs to return 206 instead of 200 ? (just guessing, I haven't checked what the current behavior is)

**Comment by VicDeo** [comment] 2015-11-04 17:23
@PVince81 Needs to be retested with https://github.com/owncloud/apps/pull/2111 applied.
DAV does return 206 for partial content https://github.com/owncloud/3rdparty/blob/master/sabre/dav/lib/DAV/CorePlugin.php#L187

**Comment by PVince81** [comment] 2015-11-09 17:22
Can anyone retry in 8.2 ? The fix is already in that version.

**Comment by freechelmi** [comment] 2015-11-09 17:50
I would say same here on upgraded 8.2 : 

https://drive.ekimia.fr/index.php/s/kkOayAYa0iefgHT

But maybe something specific to my server ?

**Comment by VicDeo** [comment] 2015-11-09 18:10
@freechelmi it's
a) not fixed for publicly shared videos 
b) movie-specific (not format, but movie)

This Big Buck Bunny (mp4) is seekable for me
http://download.blender.org/peach/bigbuckbunny_movies/

**Comment by PVince81** [comment] 2015-11-10 07:51
Raised https://github.com/owncloud/apps/issues/2120 for public page seeing.

@SergioBertolinSG can you verify non-public page seeking with big buck bunny ?

**Comment by SergioBertolinSG** [comment] 2015-11-10 08:13
I've tested in 8.2.1 (daily tarball) It works correctly, using chrome, firefox and safari.

But I've seen a problem with locking. After closing the video, you can't move the file, a warning appears telling you that it is locked.

**Comment by MorrisJobke** [comment] 2015-11-10 08:20
> But I've seen a problem with locking. After closing the video, you can't move the file, a warning appears telling you that it is locked.

This is not really related to this ticket -> please open a new issue.

I will close this issue then, because it's fixed.

**Closed by MorrisJobke** 2015-11-10 08:20 UTC
Labels: bug, sev3-medium

**Comment by freechelmi** [comment] 2015-11-10 09:47
Thanks non-shared video seekable seeked without problem. (sintel  mp4) 
I confirm the issue is fixed.

**Comment by SergioBertolinSG** [comment] 2015-11-10 09:50
@MorrisJobke Opened here https://github.com/owncloud/apps/issues/2121

**Comment by PVince81** [comment] 2015-11-10 10:09
(and now I feel like watching Elephant's dream again, thanks guys)
