### ISSUE TITLE
External storage: Dropbox webhooks

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/apps#1812] opened 2014-06-05 16:04 UTC
I'm posting this here as a reminder that [Dropbox announced webhooks](https://www.dropbox.com/developers/blog/90/announcing-dropbox-webhooks). It would be cool if ownCloud external storage could use this to sync with Dropbox.

**Comment by dhuyvetter** [comment] 2015-06-19 12:00
They have webhooks now, got the option to set it up when creating a Dropbox app to connect to my ownCloud.

**Comment by PVince81** [comment] 2015-07-30 09:49
Duplicate of https://github.com/owncloud/core/issues/10139

**Closed by PVince81** 2015-07-30 09:49 UTC
Labels: app:external, Enhancement
